### ISSUE TITLE
Setting unknown property: kartik\widgets\DatePicker::_container

### ISSUE THREAD

**Issue by 140toesandfingers** [gugoan/economizzer#130]
PHP 7.1. 

yii\base\UnknownPropertyException: Setting unknown property: kartik\widgets\DatePicker::_container in /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('_container', Array)
#1 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(kartik\widgets\DatePicker), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('kartik\\widgets\\...', Array, Array)
#5 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('kartik\\widgets\\...', Array, Array)
#6 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Widget.php(137): yii\BaseYii::createObject(Array)
#7 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/widgets/ActiveField.php(781): yii\base\Widget::widget(Array)
#8 /home/breederdaron/public_html/WORKING/economizzer/vendor/kartik-v/yii2-widget-datepicker/DatePicker.php(314): yii\widgets\ActiveField->widget('kartik\\widgets\\...', Array)
#9 /home/breederdaron/public_html/WORKING/economizzer/vendor/kartik-v/yii2-widget-datepicker/DatePicker.php(247): kartik\date\DatePicker->renderInput()
#10 /home/breederdaron/public_html/WORKING/economizzer/vendor/kartik-v/yii2-widget-datepicker/DatePicker.php(215): kartik\date\DatePicker->renderDatePicker()
#11 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Widget.php(140): kartik\date\DatePicker->run()
#12 /home/breederdaron/public_html/WORKING/economizzer/views/cashbook/_form.php(42): yii\base\Widget::widget(Array)
#13 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/View.php(336): require('/home/breederda...')
#14 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/breederda...', Array)
#15 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/breederda...', Array, NULL)
#16 /home/breederdaron/public_html/WORKING/economizzer/views/cashbook/create.php(14): yii\base\View->render('_form', Array)
#17 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/View.php(336): require('/home/breederda...')
#18 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/breederda...', Array)
#19 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/home/breederda...', Array, Object(app\controllers\CashbookController))
#20 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('create', Array, Object(app\controllers\CashbookController))
#21 /home/breederdaron/public_html/WORKING/economizzer/controllers/CashbookController.php(88): yii\base\Controller->render('create', Array)
#22 [internal function]: app\controllers\CashbookController->actionCreate()
#23 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#25 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array)
#26 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('cashbook/create', Array)
#27 /home/breederdaron/public_html/WORKING/economizzer/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#28 /home/breederdaron/public_html/WORKING/economizzer/web/index.php(12): yii\base\Application->run()
#29 {main}

**Comment by 140toesandfingers** [comment]
Adding this note on the install. 

$ composer global require "fxp/composer-asset-plugin:^1.3.1"
Changed current directory to /home/breederdaron/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing fxp/composer-asset-plugin (v1.4.2)
    Loading from cache


Fatal error: Uncaught Error: Call to undefined method Composer\Package\RootPackage::getConfig() in /home/breederdaron/.composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php:111
Stack trace:
#0 /home/breederdaron/.composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php(74): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::getConfigBase(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 /home/breederdaron/.composer/vendor/fxp/composer-asset-plugin/FxpAssetPlugin.php(82): Fxp\Composer\AssetPlugin\Config\ConfigBuilder::build(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 phar:///opt/cpanel/composer/bin/composer/src/Composer/Plugin/PluginManager.php(230): Fxp\Composer\AssetPlugin\FxpAssetPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///opt/cpanel/composer/bin/composer/src/Composer/Plugin/PluginManager.php(203): Composer\Plugin\PluginManager->addPlugin(Object(Fxp\Composer\AssetPlugin\FxpAssetPlugin))
#4 phar:///opt/cpanel/composer/bin/composer/sr in /home/breederdaron/.composer/vendor/fxp/composer-asset-plugin/Config/ConfigBuilder.php on line 111

**Comment by 140toesandfingers** [comment]
These have been corrected onsite.
